# This file will override the settings in the Netlify UI.
[build]
  # Base directory is set to "website/" in the Netlify UI.
  # This command will be run from within the "website/" directory.
  command = "pnpm run build"
  
  # This path is relative to the Base directory.
  # Netlify will look for "website/dist".
  publish = "dist"

# This path is relative to the root of the repository.
# Netlify will look for "website/netlify/functions".
[functions]
  directory = "website/netlify/functions"

[[redirects]]
  from = "/api/chat/*"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200
