[build]
  base = "website"
  command = "pnpm build"
  publish = "dist"

[functions]
  directory = "website/.netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200