[build]
  base = "/"
  command = """
    npm i -g pnpm &&
    pnpm install &&
    pnpm run jsdoc-json -- --destination website/public/doc.json &&
    cd website &&
    pnpm install &&
    pnpm add @astrojs/netlify cssesc &&
    pnpm astro sync &&
    pnpm build
  """
  publish = "website/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NETLIFY = "true"

[dev]
  framework = "astro"
  targetPort = 4321
  port = 9000
  functionsPort = 9000

 