name: Build & Deploy

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci && cd repl && npm ci && cd ../tutorial && npm ci
      - run: npm run build
      - run: npm run deploy
